export let dictated = [
	'let name equals string 12sivanesh',
	'constant object equals 12',
	'variable dam',
	'variable dam equals false',
	'let sum equals a plus b minus c into d by e d not equal to f',
	'variable dam equals false and true',
	'function say hello',
	'arguments name comma color',
	'print name',
	'let string equals string hello plus name one',
	'return string',
	'close',
	'let name equals call say hello of string sivanesh',
	'call say hello of string sivanesh',
	'let name of thunder equals name dot replace of 1 comma true comma string hell',
	// arrow function
	'variable name equals arrow function',
	'arguments hello comma two',
	'arguments hello comma three',
	'arguments undo',
	'arguments clear',
	'close',
	'let object equals object name value string eleven',
	'age value 11',
	'hobbies value list string batminton',
	'string cricket comma 1',
	'string carrom',
	'close',
	'close',
	'let arr equals list',
	'object',
	' name value 1',
	'close',
	'12 comma string herllo',
	'arrow function',
	'arguments one comma two',
	'let name equals 65',
	'return name',
	'close',
	'next',
	'close',
	'call say hello of string arguments comma true comma 12',
	// Calling normally without equals without work
	'name equals hello world dot substring of string words',
	'undo',
	'list'
];
